import type { SourcedContent } from "./types";

export interface ExperienceRecord extends SourcedContent {
  role: string;
  organization: string;
  period: string;
  highlights: string[];
}

export const experience: ExperienceRecord[] = [
  { id: "experience-osu-va-oracle-2026", source: "Updated CV", role: "AI/ML Engineer Intern", organization: "Oklahoma State University, Department of Veterans Affairs & Oracle", period: "May 2026 - Present", highlights: ["Delivered enterprise-scale AI, LLM, and agentic decision-support solutions across federally funded DoD, NSF, and USDA programs in federated healthcare environments supporting 1.95M+ patients and 90K+ clinical features; model performance reached 0.916 AUC.", "Translated Python ML workflows into JavaScript for browser-based inference, retaining 100% of inference data locally and eliminating external model-serving data transfers."] },
  { id: "experience-osu-chsi-2025-2026", source: "Updated CV", role: "AI/ML Researcher & Engineer (Research Assistant)", organization: "Oklahoma State University, Center for Health Systems Innovation, Cerner", period: "September 2025 - April 2026", highlights: ["Architected LLM-powered RAG and agentic AI systems integrating vector retrieval, healthcare analytics, lightweight tool connectivity, and retrieval-reranking-critic validation.", "Defined evaluation frameworks, KPIs, and validation strategies for task success, hallucination detection, and safety across a $2.7M DoD-funded research program."] },
  { id: "experience-gsk-2025", source: "Updated CV", role: "Data Science and Machine Learning Intern", organization: "GlaxoSmithKline - Digital Virology R&D", period: "May 2025 - August 2025", highlights: ["Developed transformer and GNN-based models for infectious disease incidence forecasting and Python pipelines integrating Google Trends and epidemiological datasets.", "Conducted multiple sequence alignment and phylogenetic analysis using MAFFT, IQ-TREE, Biopython, and statistical tools."] },
  { id: "experience-osu-chsi-2023-2025", source: "Updated CV", role: "AI/ML Researcher & Engineer (Research Assistant)", organization: "Oklahoma State University, Center for Health Systems Innovation, Cerner", period: "May 2023 - April 2025", highlights: ["Built Spark ML/NLP pipelines on Oracle-Cerner EHR data, improving operational efficiency by 15%, processing speed by 20%, storage utilization by 20%, and reducing model training time by 25%.", "Led attention-based GNN models for post-traumatic epilepsy risk prediction on large-scale sparse EHR data."] },
  { id: "experience-osu-nsf-2021-2023", source: "Updated CV", role: "AI/ML Researcher & Engineer (Research Assistant)", organization: "Oklahoma State University, Computer Vision and Understanding Lab, NSF grant", period: "January 2021 - April 2023", highlights: ["Designed knowledge-graph-enhanced agentic QA and decision-support systems integrating ConceptNet, dependency parsing, and POS tagging across 1M+ records; improved answer quality by 15%.", "Built QA agents using transformer models, retrieval pipelines, and commonsense reasoning."] },
  { id: "experience-osu-usda-2020", source: "Updated CV", role: "AI/ML Researcher & Engineer (Research Assistant)", organization: "Oklahoma State University, USDA grant", period: "May 2020 - December 2020", highlights: ["Developed taxonomy-aware zero-shot ML for biological sequence classification in limited-label settings."] },
  { id: "experience-osu-2019-2020", source: "Updated CV", role: "AI/ML Researcher & Engineer (Research Assistant)", organization: "Oklahoma State University", period: "August 2019 - April 2020", highlights: ["Improved fake-news detection accuracy from 87% to 93% using propagation-path classification with CNN and LSTM architectures.", "Developed NLP and statistical ML models for opioid-risk detection and diabetic patient outcomes, achieving a 20% accuracy improvement over standard benchmarks."] },
  { id: "experience-globallogic-2019", source: "Updated CV", role: "Senior Software Engineer (AI/ML)", organization: "GlobalLogic, Walgreens", period: "February 2019 - July 2019", highlights: ["Established Apache Spark parallel-computing pipelines for large datasets and real-time analytics using cloud resources."] },
  { id: "experience-capgemini-2017-2019", source: "Updated CV", role: "Senior Consultant (AI/ML)", organization: "Capgemini America, McDonald's", period: "June 2017 - February 2019", highlights: ["Led ML model deployment in microservices using Docker, Kubernetes, REST APIs, and MLOps frameworks, achieving a 25% performance improvement.", "Applied CI/CD and time-series analysis for business profit forecasting, with a 20% lift in digital revenue alongside the Mobile Order & Pay rollout."] },
  { id: "experience-santa-clara-2016-2017", source: "Updated CV", role: "Information Systems Manager Intern (Data Science)", organization: "County of Santa Clara", period: "June 2016 - April 2017", highlights: ["Managed five concurrent projects and deployed predictive modeling with ensemble techniques and statistical ML baselines, enhancing prediction accuracy by 40%."] },
  { id: "experience-doosan-2013-2015", source: "Updated CV", role: "Senior Software Engineer (ML)", organization: "Hyundai (Doosan) Infracore-Bobcat", period: "March 2013 - July 2015", highlights: ["As Solution Architect, led a 25-member team on the North America Parts Dealer Portal; modeling contributed to a 15-20% lift in digital parts revenue across 200+ dealers and cut support/returns costs by over $2M."] },
  { id: "experience-infosys-2011-2013", source: "Updated CV", role: "Data Analyst", organization: "Infosys Technology Solutions", period: "December 2011 - January 2013", highlights: ["Defined functional requirements, process diagrams, and reports; redesigned a website using AngularJS, HTML, Bootstrap, and CSS."] },
  { id: "experience-tcs-2007-2011", source: "Updated CV", role: "Assistant Systems Engineer", organization: "Tata Consultancy Services", period: "March 2007 - September 2011", highlights: ["Engineered, deployed, and validated front-end and Java/J2EE back-end systems for a successful product launch."] },
];