import type { SourcedContent } from "./types";

export interface PublicationRecord extends SourcedContent { year: string; title: string; venue: string; contribution: string; citation: string; url: string | null; linkPlaceholder: string; }

export const publications: PublicationRecord[] = [
  { id: "publication-isd-qa-icpr-2022", source: "Updated CV", year: "2022", title: "ISD-QA: Iterative Distillation of Commonsense Knowledge from General Language Models for Unsupervised Question Answering", venue: "Proceedings of the 26th International Conference on Pattern Recognition (ICPR)", contribution: "Iterative commonsense-knowledge distillation for unsupervised question answering.", citation: "Ramamurthy, P. & Aakur, S. N. ISD-QA: Iterative Distillation of Commonsense Knowledge from General Language Models for Unsupervised Question Answering. Proceedings of the 26th International Conference on Pattern Recognition (ICPR).", url: null, linkPlaceholder: "Add publication URL" },
  { id: "publication-rich-recipe-keps-2022", source: "Updated CV", year: "2022", title: "A Rich Recipe Representation as Plan to Support Expressive Multi-Modal Queries on Recipe Content and Preparation Process", venue: "KEPS Workshop, International Conference on Automated Planning and Scheduling (ICAPS)", contribution: "A plan representation for expressive multimodal queries on recipe content and preparation.", citation: "Pallagani, V., Ramamurthy, P., Khandelwal, V., Venkataramanan, R., Lakkaraju, K., Aakur, S. N., & Srivastava, B. A Rich Recipe Representation as Plan to Support Expressive Multi-Modal Queries on Recipe Content and Preparation Process. KEPS Workshop, ICAPS.", url: null, linkPlaceholder: "Add publication URL" },
  { id: "publication-allergy-recipe-aaai-2022", source: "Updated CV", year: "2022", title: "A Multi-Modal Decision Support System with Allergy-Aware Recipe Understanding Powered by a Plan Representation", venue: "AAAI affiliated demonstration/workshop paper", contribution: "Allergy-aware recipe understanding using a plan representation for multimodal decision support.", citation: "Khandelwal, V., Lakkaraju, K., Pallagani, V., Ramamurthy, P., et al. A Multi-Modal Decision Support System with Allergy-Aware Recipe Understanding Powered by a Plan Representation. AAAI affiliated demonstration/workshop paper.", url: null, linkPlaceholder: "Add publication URL" },
  { id: "publication-tepi-jbhi-2024", source: "Updated CV", year: "2024", title: "TEPI: Taxonomy-Aware Embedding and Pseudo-Imaging for Scarcely-Labeled Zero-Shot Genome Classification", venue: "IEEE Journal of Biomedical and Health Informatics (JBHI)", contribution: "Taxonomy-aware embeddings and pseudo-imaging for zero-shot genome classification with scarce labels.", citation: "Aakur, S. N., Ramnath, V., Ramamurthy, P., et al. TEPI: Taxonomy-Aware Embedding and Pseudo-Imaging for Scarcely-Labeled Zero-Shot Genome Classification. IEEE Journal of Biomedical and Health Informatics (JBHI).", url: null, linkPlaceholder: "Add publication URL" },
  { id: "publication-epilepsy-risk-ijmi-2025", source: "Updated CV", year: "2025", title: "Graph Attention Network with Comorbidity Connectivity Embedding for Post-Traumatic Epilepsy Risk Prediction Using Sparse Time-Series Electronic Health Records", venue: "International Journal of Medical Informatics (IJMI)", contribution: "Post-traumatic epilepsy risk prediction using graph attention and comorbidity connectivity embeddings on sparse time-series EHRs.", citation: "Ramamurthy, P., et al. Graph Attention Network with Comorbidity Connectivity Embedding for Post-Traumatic Epilepsy Risk Prediction Using Sparse Time-Series Electronic Health Records. International Journal of Medical Informatics (IJMI). Abstract accepted for poster presentation at the American Epilepsy Society Annual Meeting, December 2025.", url: null, linkPlaceholder: "Add publication URL" },
];